In [1]:
import pandas as pd
import numpy as np
import ast
import math

# Function to calculate the Probability 
def Probability(rating1, rating2):
    return 1. / (1. + (10**( (rating1 - rating2) / 400) ))

def GetScaling(formula,point_diff,ranking_diff):
    if formula:
        K = 40
        kdiff = point_diff / 9 + 0.25
    else:
        K = 50
        alpha = 1.5
        kdiff = np.log( 1. + point_diff ) * (alpha / (alpha - ranking_diff / 1000))
    return K*kdiff
# Function to calculate Elo rating 
def EloRating(R1, R2, pt1, pt2, formula = 0):    
    #Get scaling (rate of change as a function of elo and point difference)
    scaling_coeff = GetScaling(formula,abs(pt1-pt2),R2-R1)        
    # Calculate the Winning Probability of Players 1 and 2
    P1 = Probability(R2, R1) #Probability for player 2 to win versus player 1        
    #If player 1 wins ==) int(pt1>pt2) = 1 ==) (int(pt1>pt2) - P1) = P2
    #If player 2 wins ==) int(pt1>pt2) = 0 ==) (int(pt1>pt2) - P1) = -P1
    elo_modification = round(scaling_coeff * (int(pt1>pt2) - P1), 0) #Change in elo for both players      
    #Update ranking
    R1 += elo_modification
    R2 -= elo_modification
    return [R1, R2]

folder=''
filename_i = folder+'2022.txt'      
with open(filename_i, mode='r') as infile:
    df = pd.read_csv(infile, sep='\t')  
listPlayers = np.array(['David', 'Martin', 'Mauro', 'Mekha', 'Romain', 'Thierry', 'Constant', 'Lucie', 'Hugo'])
startingElo = np.array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])
newElo = startingElo

for idx, row in df.iterrows():
    print(newElo)
    mask = np.logical_or(listPlayers == row['Player1'], listPlayers == row['Player2'])    
    currentElo_players = newElo[mask]
    score_newformula = EloRating(currentElo_players[0], currentElo_players[1], row['Score1'], row['Score2'])
    newElo[mask]  = score_newformula

print(newElo)

[1000 1000 1000 1000 1000 1000 1000 1000 1000]
[1049 1000  951 1000 1000 1000 1000 1000 1000]
[1049 1041  910 1000 1000 1000 1000 1000 1000]
[1049 1070  881 1000 1000 1000 1000 1000 1000]
[1049 1092  859 1000 1000 1000 1000 1000 1000]
[1049 1092  859 1000 1049  951 1000 1000 1000]
[1049 1092  942 1000  966  951 1000 1000 1000]
[1049 1092  995 1000  913  951 1000 1000 1000]
[1049 1092 1036 1000  913  910 1000 1000 1000]
[1049 1092 1036 1049  913  910  951 1000 1000]
[1049 1092 1036 1082  913  910  918 1000 1000]
[1049 1115 1036 1082  913  887  918 1000 1000]
[1049 1115 1062 1082  913  861  918 1000 1000]
[1100 1115 1011 1082  913  861  918 1000 1000]
[1134 1115  977 1082  913  861  918 1000 1000]
[1159 1115  952 1082  913  861  918 1000 1000]
[1179 1115  932 1082  913  861  918 1000 1000]
[1195 1115  916 1082  913  861  918 1000 1000]
[1209 1115  902 1082  913  861  918 1000 1000]
[1140 1115  971 1082  913  861  918 1000 1000]
[1077 1115 1034 1082  913  861  918 1000 1000]
[1077 1058 10